name: CI

on:
  workflow_dispatch:
  issues:

jobs:
  run:
    name: Run CI scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout benchmarks repository
        uses: actions/checkout@v2

      - name: Download pre-build ci-scripts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-ci-scripts.yml
          repo: 'iocost-benchmark/iocost-benchmarks-ci'

      - name: Set CI script permissions
        run: |
          chmod +x iocost-benchmarks-ci/benchmark-database-ci
          # resctl-bench isn't yet included
          # chmod +x iocost-benchmarks-ci/resctl-demo/target/release/resctl-bench

      - name: Run CI scripts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: iocost-benchmarks-ci/benchmark-database-ci issue-event
