name: Issue event

on:
  issues:

jobs:
  run:
    name: Run ci-scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout benchmarks repository
        uses: actions/checkout@v2

      - name: Download pre-build ci-scripts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-ci-scripts.yml
          repo: 'iocost-benchmark/ci-scripts'

      - name: Set permissions on ci-scripts
        run: |
          chmod +x ci-scripts/benchmark-database-ci
#          chmod +x ci-scripts/ci-scripts/target/release/benchmark-database-ci
#          chmod +x ci-scripts/resctl-demo/target/release/resctl-bench

      - name: Smoke-test benchmark-database-ci
        #run: ci-scripts/ci-scripts/target/release/benchmark-database-ci --help
        run: ci-scripts/benchmark-database-ci --help

#      - name: Smoke-test resctl-bench
#        run: ci-scripts/resctl-demo/target/release/resctl-bench --help

      - name: Run CI script for issue event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        #run: ci-scripts/ci-scripts/target/release/benchmark-database-ci issue-event
        run: ci-scripts/benchmark-database-ci issue-event
